[package]
name = "riff"
version = "0.1.0"
authors = ["Johan Walles <johan.walles@gmail.com>"]
edition = "2018"
repository = "https://github.com/walles/riff/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffus = "0.9.1"
regex = "1"
lazy_static = "1.4.0"
isatty = "0.1.9"

[dev-dependencies]
pretty_assertions = "0.6.1"
