on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # For testing cross compiling to Windows
      - uses: egor-tensin/setup-mingw@v2

      - run: ./ci.sh
